name: Deploy CD

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm deploy
        uses: actions/npm@master
        with:
          args: run deploy
        env: 
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_LOCALROOT: ${{ secrets.FTP_LOCALROOT }}
          FTP_REMOTEROOT: ${{ secrets.FTP_REMOTEROOT }}
